// <auto-generated />
namespace CorporateAndFinance.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ComapnyBankTransactionToCompanyBankIDField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ComapnyBankTransactionToCompanyBankIDField));
        
        string IMigrationMetadata.Id
        {
            get { return "201704100949229_ComapnyBankTransaction-ToCompanyBankID-Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
