//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client is required..
        /// </summary>
        internal static string MSG_CATEGORY_CLIENT_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_CATEGORY_CLIENT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant is required..
        /// </summary>
        internal static string MSG_CATEGORY_CONSULTANT_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_CATEGORY_CONSULTANT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor is required..
        /// </summary>
        internal static string MSG_CATEGORY_VENDOR_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_CATEGORY_VENDOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone already has that email. Try another?.
        /// </summary>
        internal static string MSG_EMAIL_NA {
            get {
                return ResourceManager.GetString("MSG_EMAIL_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From inter company to same inter company bank transaction not allowed..
        /// </summary>
        internal static string MSG_FROM_INTER_COMAPNY_TO_SAME_COMAPANY_NOTALLOWED {
            get {
                return ResourceManager.GetString("MSG_FROM_INTER_COMAPNY_TO_SAME_COMAPANY_NOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, System couldn&apos;t add new {0}. Please try again or contact your site Administrator..
        /// </summary>
        internal static string MSG_GENERIC_ADD_FAILED {
            get {
                return ResourceManager.GetString("MSG_GENERIC_ADD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} added successfully..
        /// </summary>
        internal static string MSG_GENERIC_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_GENERIC_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does&apos;t contain {0} column, Please make sure all column exist in sheet..
        /// </summary>
        internal static string MSG_GENERIC_COLUMN_MISSING {
            get {
                return ResourceManager.GetString("MSG_GENERIC_COLUMN_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record couldn&apos;t be delete. Please try again or contact your site Administrator..
        /// </summary>
        internal static string MSG_GENERIC_DELETE_FAILED {
            get {
                return ResourceManager.GetString("MSG_GENERIC_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have rights to delete older record..
        /// </summary>
        internal static string MSG_GENERIC_DELETE_RECORD {
            get {
                return ResourceManager.GetString("MSG_GENERIC_DELETE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully..
        /// </summary>
        internal static string MSG_GENERIC_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_GENERIC_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes couldn&apos;t be saved. Please try again or contact your software vendor..
        /// </summary>
        internal static string MSG_GENERIC_FAILED {
            get {
                return ResourceManager.GetString("MSG_GENERIC_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have rights to update older record..
        /// </summary>
        internal static string MSG_GENERIC_RESTRICTED_UPDATE_RECORD {
            get {
                return ResourceManager.GetString("MSG_GENERIC_RESTRICTED_UPDATE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved successfully..
        /// </summary>
        internal static string MSG_GENERIC_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_GENERIC_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, System couldn&apos;t update {0}. Please try again or contact your site Administrator..
        /// </summary>
        internal static string MSG_GENERIC_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("MSG_GENERIC_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} successfully..
        /// </summary>
        internal static string MSG_GENERIC_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_GENERIC_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, System couldn&apos;t upload new {0} file. Please try again or contact your site Administrator..
        /// </summary>
        internal static string MSG_GENERIC_UPLOAD_ERROR {
            get {
                return ResourceManager.GetString("MSG_GENERIC_UPLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} uploaded successfully..
        /// </summary>
        internal static string MSG_GENERIC_UPLOAD_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_GENERIC_UPLOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number {0} is not assigned to user {1} in system. please contact your site Administrator.
        /// </summary>
        internal static string MSG_GENERIC_UPLOAD_USERCARD_ERROR {
            get {
                return ResourceManager.GetString("MSG_GENERIC_UPLOAD_USERCARD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory column {0} does not contain value at row number {1} . &lt;br /&gt;.
        /// </summary>
        internal static string MSG_GENERIC_UPLOAD_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("MSG_GENERIC_UPLOAD_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request can&apos;t be fulfil at this time. Please try again later or your software vendor..
        /// </summary>
        internal static string MSG_LOGIN_ERROR {
            get {
                return ResourceManager.GetString("MSG_LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Password is incorrect..
        /// </summary>
        internal static string MSG_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("MSG_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged in. Feel free to browse the admin panel. Redirecting....
        /// </summary>
        internal static string MSG_LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification couldn&apos;t be sent to one or more user(s)..
        /// </summary>
        internal static string MSG_NOTIFICATION_FAILED {
            get {
                return ResourceManager.GetString("MSG_NOTIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification has been sent to selected user(s)..
        /// </summary>
        internal static string MSG_NOTIFICATION_SENT {
            get {
                return ResourceManager.GetString("MSG_NOTIFICATION_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        internal static string MSG_PASSWORD_RESET_REQUEST_FAILED {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_RESET_REQUEST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link has been sent to your email address..
        /// </summary>
        internal static string MSG_PASSWORD_RESET_REQUEST_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_RESET_REQUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted Access.
        /// </summary>
        internal static string MSG_RESTRICTED_ACCESS {
            get {
                return ResourceManager.GetString("MSG_RESTRICTED_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction couldn&apos;t be saved. Please try again or contact your site Administrator..
        /// </summary>
        internal static string MSG_TRANSACTION_FAILED {
            get {
                return ResourceManager.GetString("MSG_TRANSACTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction saved successfully..
        /// </summary>
        internal static string MSG_TRANSACTION_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_TRANSACTION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account number {0} not assigned to any user at row number {1} . &lt;br /&gt;.
        /// </summary>
        internal static string MSG_UPLOAD_ACCOUNT_NUMBER_NOTASSIGN {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_ACCOUNT_NUMBER_NOTASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format exist on column {0} at row number {1}.  &lt;br /&gt;.
        /// </summary>
        internal static string MSG_UPLOAD_INVALID_DATE_FORMAT {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_INVALID_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount format exist on column {0} at row number {1} . &lt;br /&gt;.
        /// </summary>
        internal static string MSG_UPLOAD_INVALID_DECIMAL_FORMAT {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_INVALID_DECIMAL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number format exist on column {0} at row number {1} . &lt;br /&gt;.
        /// </summary>
        internal static string MSG_UPLOAD_INVALID_NUMBER_FORMAT {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_INVALID_NUMBER_FORMAT", resourceCulture);
            }
        }
    }
}
